#### importation de packages 

In [11]:
import numpy as np 
from scipy.sparse import csr_matrix
from scipy.sparse.csgraph import minimum_spanning_tree


In [9]:
M = np.zeros(shape=(4, 4 ))
M[0,1]= 8
M[0,3] = 3
M[1,2] = 2 
M[1,3] = 5 
M[2,3] = 6 

In [10]:
M 

array([[0., 8., 0., 3.],
       [0., 0., 2., 5.],
       [0., 0., 0., 6.],
       [0., 0., 0., 0.]])

In [7]:
#indice_ligne  = np.array([0,0,1,1,2])
#indice_colone = np.array([1,3,2,3,3])
#data_colone = np.array([8,3,2,5,6])


In [13]:
M_csr = csr_matrix(M)

In [16]:
res = minimum_spanning_tree(M_csr)


In [18]:
res.toarray()

array([[0., 0., 0., 3.],
       [0., 0., 2., 5.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
poids = res.toarray().sum()

In [20]:
poids 

10.0

In [21]:
A = np.array([
    [1,2,1],
    [1,1,1],
    [0,0,0]
])

In [23]:
B = np.array(
    [
    [1,0,1],
    [0,0,1],
    [0,0,0]
    ]
)

In [24]:
A@B

array([[1, 0, 3],
       [1, 0, 2],
       [0, 0, 0]])

In [25]:
B@A

array([[1, 2, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [32]:
A = np.ones(shape=(3,3))
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
A[0,0] =-1
A[1,1] = -1 
A[2,2] =-1

In [42]:
A_carre = A@A
A_carre

array([[ 3., -1., -1.],
       [-1.,  3., -1.],
       [-1., -1.,  3.]])

In [41]:
A_carre == 2*np.eye(3)-A

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [43]:
A + np.eye(3)

array([[0., 1., 1.],
       [1., 0., 1.],
       [1., 1., 0.]])

In [44]:
A


array([[-1.,  1.,  1.],
       [ 1., -1.,  1.],
       [ 1.,  1., -1.]])

In [45]:
4*9 -(6*7)

-6

In [48]:
9-21

-12

In [50]:
A = np.array([
    [1,4,7],
    [2,5,8],
    [3,6,9]
])

In [55]:
from scipy.linalg import inv, det

In [54]:
A = np.array([
    [2, 1, 3],
    [1, 0, 2],
    [2, 0, -2]
])


In [56]:
det(A)

6.0

In [57]:
L = [1,3,6,3,2,5,3,3,1]


In [62]:
d = 0 
s = 0
for indice  in range(len(L)):
    d = d + L[indice]
    




In [65]:
len(L) / 3 

3.0

In [66]:
30 - 6

24

In [67]:
30/3

10.0

In [68]:
10-6

4

In [69]:
10/3

3.3333333333333335

In [70]:
11-6

5

In [75]:
T = [ 1,2 ,3,4,5]

for i in range(len(T)):
    T[i] = T[len(T)-i-1]

In [76]:
T

[5, 4, 3, 4, 5]